framework:
    secret: '%env(APP_SECRET)%'

when@dev:
    framework:
        http_method_override: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file