services:
  symfony-app:
    build: .
    container_name: symfony-app
    working_dir: /var/www/symfony
    volumes:
      - ./symfony:/var/www/symfony
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=postgresql://symfony:symfony@postgresql:5432/symfony_db
    networks:
      - symfony-network

  nginx:
    image: nginx:alpine
    container_name: symfony-nginx
    ports:
      - "80:80"
    volumes:
      - ./symfony:/var/www/symfony
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony-app
    networks:
      - symfony-network

  postgresql:
    image: postgres:15-alpine
    container_name: symfony-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - symfony-network

  adminer:
    image: adminer
    container_name: symfony-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - symfony-network

volumes:
  postgres_data:

networks:
  symfony-network:
    driver: bridge